[base]
secret_key = "badsecret"
debug = true
admin_password = "badpassword"
media_directory = "/home/videos"  # as specified in the docker-compose

[postgresql]
url = 'postgresql://tthack-user:tthack-password@tthack-psql:5432/tthack-db'