version: "3"

services:

  psql:
    image: postgres
    container_name: tthack-psql
    environment:
      POSTGRES_DB: tthack-db
      POSTGRES_USER: tthack-user
      POSTGRES_PASSWORD: tthack-password
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - psql:/var/lib/postgresql/data:rw

  app:
    image: tthack/videohosting
    container_name: tthack-videohosting
    ports:
      - "80:80"
    restart: always
    command: sh -c "poetry run uvicorn src.main:app --host 0.0.0.0 --port 80"
    depends_on:
      - psql
    volumes:
      - backend:/home/videos

volumes:
  psql:
    driver: local
  backend: